### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by ekevra** [tritonk7/senla#100]
https://github.com/tritonk7/senla/blob/91f043d42f329dfe7dd789862426ca93712f33ca/Lecture_3.4/Aura_Component/TouristAssigmentCmp.cmp#L36

В компоненте нежелательны прописывания CSS стилей, можно это вынести в CSS файл, можно найти подходящие для разметки slds стили. Тем более эти 400 пикселей не на всех устройствах подойдут по размеру(где-то этого может быть замало или наоборот и т.д.)

**Comment by alexCherrySfds2019** [comment]
@ekevra could be closed
