### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by ekevra** [tritonk7/senla#101]
https://github.com/tritonk7/senla/blob/91f043d42f329dfe7dd789862426ca93712f33ca/Lecture_3.4/Aura_Component/TouristAssigmentCmp.cmp#L17

Names of attributes look like names of methods(with "set" word)

**Comment by alexCherrySfds2019** [comment]
@ekevra could be closed

**Comment by alexCherrySfds2019** [comment]
@alexCherrySfds2019 test
