### ISSUE TITLE
2.2 clarify the logic 

### ISSUE THREAD

**Issue by alexCherrySfds2019** [tritonk7/senla#12]
https://github.com/tritonk7/senla/blob/13a97ae8ec17154694ad1eb096a187cddc72c371/Lecture_2.2/TouristService.cls#L12

а можешь в общем рассказать как ты понял задачу и что делает метод? разбить на несколько шагов и описать что делает каждый?

**Comment by tritonk7** [comment]
я не верное понял задачу, я помечал всех туристов у которых совпадает имя и емейл, передал при помощи счетчика, если повтор больше больше одного , то отмечает их, а у которого 1 не отмечает. убрал запрос в менеджер.

**Comment by tritonk7** [comment]
Задание я так понял. нужно пробежаться по туристам после инсерта  и если есть  совпадение этих туристов по именам и емейлам, то отметить их как дупликаты, не отмечать дупликатом первый в списке б а последующие.
