### ISSUE TITLE
2.2 clarifying is needed

### ISSUE THREAD

**Issue by alexCherrySfds2019** [tritonk7/senla#16]
https://github.com/tritonk7/senla/blob/192b1d17b37fde90b8d3560c9f1f61d13d2547c9/Lecture_2.2/SearchTourist.cls#L17

это у тебя наверное логика такая, а можешь пояснить, как здесь завязана дата, и не излишний ли подзапрос (получается, у тебя поле Upcoming_Flights_Count__c не учитывает такие трипы)

**Comment by tritonk7** [comment]
Added comments

**Comment by alexCherrySfds2019** [comment]
done
