### ISSUE TITLE
2.2 move to FlightManager

### ISSUE THREAD

**Issue by alexCherrySfds2019** [tritonk7/senla#17]
https://github.com/tritonk7/senla/blob/74c4bec5f4b794e8ea54fa695702313c9fd532d7/Lecture_2.2/TouristManager.cls#L63

и заодно метод ы
https://github.com/tritonk7/senla/blob/74c4bec5f4b794e8ea54fa695702313c9fd532d7/Lecture_2.2/TouristManager.cls#L93
https://github.com/tritonk7/senla/blob/74c4bec5f4b794e8ea54fa695702313c9fd532d7/Lecture_2.2/TouristManager.cls#L103

**Comment by tritonk7** [comment]
Create new Class
