### ISSUE TITLE
2.2 KISS

### ISSUE THREAD

**Issue by alexCherrySfds2019** [tritonk7/senla#5]
https://github.com/tritonk7/senla/blob/9e4798855072b67f3ded3c57fdf2c35c0fd41f78/Lecture_2.2/TouristManager.cls#L66

а можно обойтись без Flight__c? и работать сразу с Tourists__c?

**Comment by tritonk7** [comment]
fixed
https://github.com/tritonk7/senla/blob/fb16a23ac2b1ff99b2344568df31932b1f562039/Lecture_2.2/TouristManager.cls#L56
