### ISSUE TITLE
2.2 add input validation

### ISSUE THREAD

**Issue by alexCherrySfds2019** [tritonk7/senla#7]
https://github.com/tritonk7/senla/blob/9e4798855072b67f3ded3c57fdf2c35c0fd41f78/Lecture_2.2/TouristManager.cls#L13

можно добавить валидацию импута (вдруг придет пустая строчка - зачем делать лишний запрос, это ударит по лимитам). это относится и к остальным методам

**Comment by alexCherrySfds2019** [comment]
а что будет если здесь

https://github.com/tritonk7/senla/blob/74c4bec5f4b794e8ea54fa695702313c9fd532d7/Lecture_2.2/TouristManager.cls#L17

или здесь

https://github.com/tritonk7/senla/blob/74c4bec5f4b794e8ea54fa695702313c9fd532d7/Lecture_2.2/TouristManager.cls#L35

придет null?

**Comment by tritonk7** [comment]
fixed
https://github.com/tritonk7/senla/blob/fb16a23ac2b1ff99b2344568df31932b1f562039/Lecture_2.2/TouristManager.cls#L20

**Comment by alexCherrySfds2019** [comment]
https://github.com/tritonk7/senla/blob/fb16a23ac2b1ff99b2344568df31932b1f562039/Lecture_2.2/TouristManager.cls#L20

здесь перемеудрил)
просто при таком условии если в списке будут хоть все null - база пропустит и выдаст просто туистов с незаполненным возрастом. И если ты отсеиваешь такое условие - метод вернет пустой лист даже если входящий параметр содержал много корректных данных. Но может у тебя логика такая) Спорить не буду
