### ISSUE TITLE
2.2 does this method work correct?

### ISSUE THREAD

**Issue by alexCherrySfds2019** [tritonk7/senla#9]
https://github.com/tritonk7/senla/blob/9e4798855072b67f3ded3c57fdf2c35c0fd41f78/Lecture_2.2/TouristManager.cls#L42

мне кажется он не будет фильтровать туристов как надо

**Comment by tritonk7** [comment]
Fixed
https://github.com/tritonk7/senla/blob/fb16a23ac2b1ff99b2344568df31932b1f562039/Lecture_2.2/TouristManager.cls#L17
